"""Write vastu placement results as Tcl commands for OpenROAD.

Outputs two kinds of placement:
  1. Macro placements via `place_macro` — hard, respected by all stages.
  2. Standard-cell seed positions via ODB `setLocation` / `setPlacementStatus` —
     initial positions that GPL starts from. GPL will move them, but starts
     from a clustered arrangement so the cluster structure is preserved.
"""
from __future__ import annotations

import math
from pathlib import Path
from typing import Any

from vastu.core.block import HardBlock, Placement, SoftBlock
from vastu.floorplan.hierarchy import HierarchicalResult, absolute_placements
from vastu.hints.rewrite import FloorplanProblem


def write_placement_tcl(
    problem: FloorplanProblem,
    result: HierarchicalResult,
    cluster_data: dict,
    out_path: str,
    *,
    dbu_per_micron: int = 1000,
) -> None:
    """Write macro placements and std-cell seed positions as Tcl for OpenROAD.

    Args:
        problem: The solved FloorplanProblem.
        result: The HierarchicalResult from solve_hierarchical.
        cluster_data: The raw parsed JSON dict from the cluster tree.
        out_path: Path to write the .tcl file.
        dbu_per_micron: Database units per micron (from cluster JSON).
    """
    abs_pl = absolute_placements(problem, result)

    # vastu solves in core-relative coords (its outline equals core_w x core_h
    # and starts at (0, 0)). OpenROAD's place_macro takes die-absolute coords,
    # so we translate by the core lower-left corner before emitting.
    floorplan = cluster_data.get("floorplan", {})
    core_area = floorplan.get("core_area")
    if core_area and len(core_area) == 4:
        core_x_min = float(core_area[0])
        core_y_min = float(core_area[1])
    else:
        core_x_min = 0.0
        core_y_min = 0.0

    # Build lookup: inst_name -> macro metadata from the cluster JSON
    macro_lookup: dict[str, dict] = {}
    for cluster in cluster_data.get("clusters", []):
        for m in cluster.get("macros", []):
            macro_lookup[m["inst_name"]] = m

    # Build lookup: block_name -> cluster metadata (for std-cell seeding)
    cluster_by_name: dict[str, dict] = {}
    for cluster in cluster_data.get("clusters", []):
        cluster_by_name[cluster["name"]] = cluster

    lines: list[str] = []
    lines.append("# Generated by vastu floorplan-clusters")
    lines.append("# Macro placements + std-cell seed positions for OpenROAD")
    lines.append("")
    lines.append("set block [ord::get_db_block]")
    lines.append("")

    # --- Macro placements ---
    lines.append("# === Macro placements ===")
    lines.append("# These are hard placements — respected by all downstream stages.")
    macro_count = 0
    for path, pl in abs_pl.items():
        # Path in abs_pl is <cluster_name>/<macro_inst_name>. Both parts can
        # themselves contain '/', so rsplit('/', 1) doesn't recover the real
        # inst_name. Match by suffix: walk progressively longer slash-suffixes
        # of the path until one matches a known macro inst_name.
        inst_name = None
        if path in macro_lookup:
            inst_name = path
        else:
            parts = path.split("/")
            for i in range(1, len(parts)):
                candidate = "/".join(parts[i:])
                if candidate in macro_lookup:
                    inst_name = candidate
                    break
        if inst_name is None:
            continue
        macro_info = macro_lookup[inst_name]
        # halo_x/halo_y in JSON are TOTAL (left+right); per-side offset is half.
        hx = macro_info.get("halo_x", 0) / 2.0
        hy = macro_info.get("halo_y", 0) / 2.0
        # vastu packs with inflated dimensions in core-relative coords;
        # macro sits centered in the halo padding, plus translate to die-abs.
        actual_x = pl.x + hx + core_x_min
        actual_y = pl.y + hy + core_y_min
        orient = pl.orient.value if hasattr(pl.orient, 'value') else str(pl.orient)
        orient_str = orient.replace("Orient.", "")
        lines.append(
            f"place_macro -macro_name {{{inst_name}}} "
            f"-location {{{actual_x:.4f} {actual_y:.4f}}} "
            f"-orientation {orient_str}"
        )
        macro_count += 1

    lines.append(f"# Placed {macro_count} macros")
    lines.append("")

    # --- Std-cell seed positions ---
    # Instead of dbRegion/dbGroup (which GPL ignores for INCLUSIVE regions),
    # we set initial positions for each std cell within its cluster's region.
    # GPL reads these via dbInst::isPlaced() and starts from them.
    # The cells are spread uniformly across the cluster's bounding box.
    lines.append("# === Std-cell seed positions ===")
    lines.append("# These are initial positions for GPL. GPL starts from these")
    lines.append("# positions instead of core-center, preserving cluster structure.")
    lines.append("# GPL will move cells during optimization, but the clustered")
    lines.append("# starting point biases it toward a cluster-respecting solution.")
    lines.append("")

    seed_count = 0
    seed_files: list[str] = []

    for path, pl in abs_pl.items():
        # Cluster names from RTLMP can contain '/' literally (e.g.
        # "i_cache_subsystem.i_nbdcache/sram_block_0__data_sram..."), so
        # _leaf_name(rsplit('/')) silently mis-identifies them and
        # _find_block(parts=split('/')) walks past nonexistent nested blocks.
        # Match by suffix instead — same pattern used for macros above.
        block_name = None
        if path in cluster_by_name:
            block_name = path
        else:
            parts = path.split("/")
            for i in range(1, len(parts)):
                candidate = "/".join(parts[i:])
                if candidate in cluster_by_name:
                    block_name = candidate
                    break
        if block_name is None:
            continue
        if block_name.startswith("__io_"):
            continue
        # Resolve to a Block to check kind. Top-level SoftBlocks are keyed by
        # their full cluster name in problem.blocks.
        blk = problem.blocks.get(block_name)
        if not isinstance(blk, SoftBlock):
            continue

        cluster_info = cluster_by_name[block_name]

        leaf_insts = cluster_info.get("leaf_instances", [])
        leaf_file = cluster_info.get("leaf_instances_file")

        if not leaf_insts and not leaf_file:
            continue

        # Region box in DBU (OpenROAD ODB uses integer DBU)
        x1_dbu = int(pl.x * dbu_per_micron)
        y1_dbu = int(pl.y * dbu_per_micron)
        x2_dbu = int((pl.x + pl.w) * dbu_per_micron)
        y2_dbu = int((pl.y + pl.h) * dbu_per_micron)

        n_cells = cluster_info.get("num_std_cells", len(leaf_insts))
        lines.append(f"# Seed {block_name}: {n_cells} cells in "
                      f"box ({pl.x:.1f},{pl.y:.1f})-({pl.x+pl.w:.1f},{pl.y+pl.h:.1f})")

        if leaf_file:
            # Large cluster — write a seeding script that reads the file
            seed_tcl = _write_seed_file_tcl(
                leaf_file, x1_dbu, y1_dbu, x2_dbu, y2_dbu,
                n_cells, out_path,
            )
            lines.append(seed_tcl)
            seed_count += n_cells
        elif leaf_insts:
            # Inline: spread cells across a grid within the box
            positions = _grid_spread(leaf_insts, x1_dbu, y1_dbu, x2_dbu, y2_dbu)
            if len(positions) <= 500:
                # Inline the Tcl commands
                for inst_name, x, y in positions:
                    lines.append(
                        f"set inst [$block findInst {{{inst_name}}}]"
                    )
                    lines.append(
                        f"if {{$inst != \"NULL\"}} {{ "
                        f"$inst setOrient R0; "
                        f"$inst setLocation {x} {y}; "
                        f"$inst setPlacementStatus PLACED }}"
                    )
                seed_count += len(positions)
            else:
                # Write to companion file to keep main Tcl small
                seed_file_path = _write_seed_companion(
                    positions, block_name, out_path
                )
                lines.append(f"source {seed_file_path}")
                seed_files.append(seed_file_path)
                seed_count += len(positions)

        lines.append("")

    lines.append(f"# Seeded {seed_count} std cells across clusters")
    if seed_files:
        lines.append(f"# Companion seed files: {', '.join(seed_files)}")

    Path(out_path).write_text("\n".join(lines) + "\n")


def _grid_spread(
    inst_names: list[str],
    x1: int, y1: int, x2: int, y2: int,
) -> list[tuple[str, int, int]]:
    """Spread instances uniformly across a rectangular grid in DBU.

    Returns list of (inst_name, x_dbu, y_dbu). Cells are distributed
    in row-major order across a grid that fills the box.
    """
    n = len(inst_names)
    if n == 0:
        return []

    w = max(1, x2 - x1)
    h = max(1, y2 - y1)

    # Compute grid dimensions — aim for roughly square cells
    cols = max(1, int(math.sqrt(n * w / h)))
    rows = max(1, math.ceil(n / cols))

    dx = w / max(1, cols)
    dy = h / max(1, rows)

    result = []
    for i, name in enumerate(inst_names):
        col = i % cols
        row = i // cols
        x = x1 + int(col * dx + dx * 0.1)  # small offset from grid edge
        y = y1 + int(row * dy + dy * 0.1)
        # Clamp to box
        x = min(x, x2 - 1)
        y = min(y, y2 - 1)
        result.append((name, x, y))
    return result


def _write_seed_companion(
    positions: list[tuple[str, int, int]],
    cluster_name: str,
    out_path: str,
) -> str:
    """Write seed positions to a companion Tcl file. Returns the file path."""
    # Cluster names can be 1000+ chars (RTLMP joins multiple module paths with
    # "||"). The Linux filesystem only allows 255-byte filenames, so build a
    # short, stable identifier: leading words of the safe-form name + an 8-hex
    # hash of the original cluster name.
    import hashlib
    safe_full = cluster_name.replace("/", "_").replace(" ", "_").replace("|", "_")
    digest = hashlib.sha1(cluster_name.encode("utf-8")).hexdigest()[:8]
    safe = safe_full[:120] + "_" + digest if len(safe_full) > 120 else safe_full
    companion_dir = Path(out_path).parent
    companion_dir.mkdir(parents=True, exist_ok=True)
    companion_path = companion_dir / f"vastu_seed_{safe}.tcl"

    lines = [
        f"# Seed positions for cluster {cluster_name} ({len(positions)} cells)",
        "set block [ord::get_db_block]",
    ]
    for inst_name, x, y in positions:
        lines.append(
            f"set inst [$block findInst {{{inst_name}}}]; "
            f"if {{$inst != \"NULL\"}} {{ "
            f"$inst setOrient R0; "
            f"$inst setLocation {x} {y}; "
            f"$inst setPlacementStatus PLACED }}"
        )

    companion_path.write_text("\n".join(lines) + "\n")
    return str(companion_path)


def _write_seed_file_tcl(
    leaf_file: str,
    x1: int, y1: int, x2: int, y2: int,
    n_cells: int,
    out_path: str,
) -> str:
    """Generate Tcl that reads instance names from a file and spreads them."""
    # We generate a Tcl loop that reads names and assigns grid positions
    w = max(1, x2 - x1)
    h = max(1, y2 - y1)
    cols = max(1, int(math.sqrt(n_cells * w / h)))
    dx = w // max(1, cols)
    dy = h // max(1, max(1, math.ceil(n_cells / cols)))

    leaf_path = Path(out_path).parent / leaf_file

    return f"""\
set seed_fp [open {leaf_path} r]
set seed_idx 0
while {{[gets $seed_fp seed_inst_name] >= 0}} {{
  set inst [$block findInst $seed_inst_name]
  if {{$inst != "NULL"}} {{
    set col [expr {{$seed_idx % {cols}}}]
    set row [expr {{$seed_idx / {cols}}}]
    set sx [expr {{{x1} + $col * {dx} + {int(dx * 0.1)}}}]
    set sy [expr {{{y1} + $row * {dy} + {int(dy * 0.1)}}}]
    if {{$sx > {x2 - 1}}} {{ set sx {x2 - 1} }}
    if {{$sy > {y2 - 1}}} {{ set sy {y2 - 1} }}
    $inst setOrient R0
    $inst setLocation $sx $sy
    $inst setPlacementStatus PLACED
  }}
  incr seed_idx
}}
close $seed_fp"""


def _leaf_name(path: str) -> str:
    """Get the leaf instance name from a hierarchical path."""
    return path.rsplit("/", 1)[-1] if "/" in path else path


def _find_block(problem: FloorplanProblem, path: str) -> Any:
    """Walk the problem hierarchy to find the Block for a placement path."""
    parts = path.split("/")
    cur = problem
    for part in parts:
        blk = cur.blocks.get(part)
        if blk is None:
            return None
        if hasattr(blk, "inner_problem") and blk.inner_problem is not None:
            cur = blk.inner_problem
            continue
        return blk
    return None
