"""Write vastu placement results as Tcl commands for OpenROAD."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from vastu.core.block import HardBlock, Placement, SoftBlock
from vastu.floorplan.hierarchy import HierarchicalResult, absolute_placements
from vastu.hints.rewrite import FloorplanProblem


def write_placement_tcl(
    problem: FloorplanProblem,
    result: HierarchicalResult,
    cluster_data: dict,
    out_path: str,
    *,
    dbu_per_micron: int = 1000,
) -> None:
    """Write macro placements and soft regions as Tcl commands for OpenROAD.

    Args:
        problem: The solved FloorplanProblem.
        result: The HierarchicalResult from solve_hierarchical.
        cluster_data: The raw parsed JSON dict from the cluster tree.
        out_path: Path to write the .tcl file.
        dbu_per_micron: Database units per micron (from cluster JSON).
    """
    abs_pl = absolute_placements(problem, result)

    # Build lookup: inst_name -> macro metadata from the cluster JSON
    macro_lookup: dict[str, dict] = {}
    for cluster in cluster_data.get("clusters", []):
        for m in cluster.get("macros", []):
            macro_lookup[m["inst_name"]] = m

    # Build lookup: block_name -> cluster metadata (for std-cell regions)
    cluster_by_name: dict[str, dict] = {}
    for cluster in cluster_data.get("clusters", []):
        cluster_by_name[cluster["name"]] = cluster

    lines: list[str] = []
    lines.append("# Generated by vastu floorplan-clusters")
    lines.append("# Macro placements and soft region constraints for OpenROAD")
    lines.append("")

    # --- Macro placements ---
    lines.append("# --- Macro placements ---")
    macro_count = 0
    for path, pl in abs_pl.items():
        # Check if this placed block corresponds to a macro
        inst_name = _leaf_name(path)
        if inst_name in macro_lookup:
            macro_info = macro_lookup[inst_name]
            hx = macro_info.get("halo_x", 0)
            hy = macro_info.get("halo_y", 0)
            # Subtract halo: vastu packed with inflated dimensions,
            # actual macro is centered within the halo.
            actual_x = pl.x + hx
            actual_y = pl.y + hy
            orient = pl.orient.value if hasattr(pl.orient, 'value') else str(pl.orient)
            # Convert orient enum name
            orient_str = orient.replace("Orient.", "")
            lines.append(
                f"place_macro -macro_name {{{inst_name}}} "
                f"-location {{{actual_x:.4f} {actual_y:.4f}}} "
                f"-orientation {orient_str}"
            )
            macro_count += 1

    lines.append(f"# Placed {macro_count} macros")
    lines.append("")

    # --- Soft regions for std-cell clusters ---
    lines.append("# --- Soft regions for std-cell clusters ---")
    region_count = 0
    for path, pl in abs_pl.items():
        block_name = _leaf_name(path)
        # Check if this is a std-cell cluster (SoftBlock in the problem tree)
        blk = _find_block(problem, path)
        if not isinstance(blk, SoftBlock):
            continue
        # Skip IO boundary blocks
        if block_name.startswith("__io_"):
            continue

        cluster_info = cluster_by_name.get(block_name)
        if cluster_info is None:
            continue

        # Region coordinates (in microns — OpenROAD Tcl commands accept microns)
        x1, y1 = pl.x, pl.y
        x2, y2 = pl.x + pl.w, pl.y + pl.h

        safe_name = block_name.replace("/", "_").replace(" ", "_")
        region_name = f"vastu_{safe_name}_region"
        group_name = f"vastu_{safe_name}_group"

        lines.append(f"# Region for {block_name} "
                      f"({cluster_info.get('num_std_cells', '?')} std cells)")
        lines.append(f"create_region {region_name}")
        lines.append(f"add_region_rect {region_name} "
                      f"{x1:.4f} {y1:.4f} {x2:.4f} {y2:.4f}")
        lines.append(f"create_group {group_name} -region {region_name}")

        # Write instance membership
        leaf_insts = cluster_info.get("leaf_instances", [])
        leaf_file = cluster_info.get("leaf_instances_file")

        if leaf_file:
            # Instance list in a separate file — source it
            lines.append(f"# Instance list from {leaf_file}")
            inst_list_path = Path(out_path).parent / leaf_file
            lines.append(f"set fp [open {inst_list_path} r]")
            lines.append(f"while {{[gets $fp inst_name] >= 0}} {{")
            lines.append(f"  catch {{group_add_member {group_name} $inst_name}}")
            lines.append(f"}}")
            lines.append(f"close $fp")
        elif leaf_insts:
            # Inline instance list
            if len(leaf_insts) <= 100:
                for inst in leaf_insts:
                    lines.append(
                        f"catch {{group_add_member {group_name} {inst}}}"
                    )
            else:
                # Write to a companion file to keep Tcl manageable
                inst_file = Path(out_path).with_suffix("") / f"{safe_name}_insts.txt"
                inst_file.parent.mkdir(parents=True, exist_ok=True)
                inst_file.write_text("\n".join(leaf_insts) + "\n")
                lines.append(f"set fp [open {inst_file} r]")
                lines.append(f"while {{[gets $fp inst_name] >= 0}} {{")
                lines.append(f"  catch {{group_add_member {group_name} $inst_name}}")
                lines.append(f"}}")
                lines.append(f"close $fp")

        lines.append("")
        region_count += 1

    lines.append(f"# Created {region_count} soft regions")

    Path(out_path).write_text("\n".join(lines) + "\n")


def _leaf_name(path: str) -> str:
    """Get the leaf instance name from a hierarchical path."""
    return path.rsplit("/", 1)[-1] if "/" in path else path


def _find_block(problem: FloorplanProblem, path: str) -> Any:
    """Walk the problem hierarchy to find the Block for a placement path."""
    parts = path.split("/")
    cur = problem
    for part in parts:
        blk = cur.blocks.get(part)
        if blk is None:
            return None
        if hasattr(blk, "inner_problem") and blk.inner_problem is not None:
            cur = blk.inner_problem
            continue
        return blk
    return None
